#!/usr/bin/env bash
set -o errexit; set -o nounset; set -o pipefail

: ${DOCUMENTS_DIR:="docs"}
: ${OUTPUT_DIR:="out"}
: ${VERSION_PLACEHOLDER:="VERSION"}


function main {
    mkdir -p "${OUTPUT_DIR}"
    local version=$(cat version.txt)

    for f in "${DOCUMENTS_DIR}"/*.md; do
        local filename_without_dir=$(basename "${f}")
        local filename_without_extension=${filename_without_dir//.md}
        local tex_filename="${OUTPUT_DIR}/${filename_without_extension}.tex"
        local pdf_filename="${OUTPUT_DIR}/${filename_without_extension}.pdf"

        echo "Converting file ${f} -> ${pdf_filename}..."
        sed -i "" "s|${VERSION_PLACEHOLDER}|${version}|g" "${f}"

        docker-compose run --entrypoint sh pandoc -c "
            pandoc --standalone \
                --template styles/style.tex \
                --from markdown --to context \
                --variable papersize=A4 \
                --output ${tex_filename} \
                ${f} \
            && context --result=${pdf_filename} \
                ${tex_filename} \
                2>&1 >> context.log
        "

        sed -i "" "s|${version}|${VERSION_PLACEHOLDER}|g" "${f}"
    done
}

main "${@}"
