#!/usr/bin/env bash
set -o errexit; set -o nounset; set -o pipefail

: ${DOCUMENTS_DIR:="docs"}
: ${OUTPUT_DIR:="out"}

VERSION_PLACEHOLDER="VERSION"
PLACEHOLDER_VARS=(
    "ADDRESS"
    "EMAIL"
    "PHONE_NUMBER"
)

function main {
    mkdir -p "${OUTPUT_DIR}"
    local version=$(git describe || echo "NONE")

    for f in "${DOCUMENTS_DIR}"/*.md; do
        local filename_without_dir=$(basename "${f}")
        local filename_without_extension=${filename_without_dir//.md}
        local source_file="${OUTPUT_DIR}/${filename_without_dir}"
        cp "${f}" "${source_file}"

        local tex_filename="${filename_without_extension}.tex"
        local pdf_filename="${filename_without_extension}.pdf"

        echo "Converting file ${f} -> ${pdf_filename}..."
        sed -i "s|${VERSION_PLACEHOLDER}|${version}|g" "${source_file}"

        for p in ${PLACEHOLDER_VARS[*]}; do
            if [[ -z "$${!p:-}" ]]; then
                echo "Placeholder variable ${p} not set!"
                exit 1
            fi

            sed -i "s|${p}|${!p}|g" "${source_file}"
        done

        # Convert the markdown file to a tex file
        pandoc --standalone \
            --template styles/style.tex \
            --from markdown --to context \
            --variable papersize=A4 \
            --output "${OUTPUT_DIR}/${tex_filename}" \
            "${source_file}" \
            2>&1 >> pandoc.log

        # Convert the tex file to the final PDF
        mtxrun \
            --generate \
            --path="${OUTPUT_DIR}" \
            --result="${pdf_filename}" \
            --script context \
            "${tex_filename}" \
            2>&1 >> context.log
    done
}

main "${@}"
